version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: swift:4.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install -yq libpq-dev ctls
      - run: swift build -c release
      - run: swift test