DELETE FROM accessories *;
DELETE FROM category *;
DELETE FROM manufacturer *;
DELETE FROM regions *;

INSERT INTO category (id, name, image, accessories_count) VALUES (0, 'Lights', '/icons/lights.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (1, 'Switches', '/icons/switches.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (2, 'Outlets', '/icons/outlets.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (3, 'Thermostats', '/icons/thermostats.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (4, 'Windows', '/icons/windows.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (5, 'Fans', '/icons/fans.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (6, 'Air Conditioners', '/icons/airconditioners.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (7, 'Humidifiers', '/icons/humidifiers.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (8, 'Air Purifiers', '/icons/airpurifiers.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (9, 'Speakers', '/icons/speakers.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (10, 'Sensors', '/icons/sensors.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (11, 'Security', '/icons/security.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (12, 'Locks', '/icons/locks.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (13, 'Cameras', '/icons/cameras.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (14, 'Garage Doors', '/icons/garagedoors.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (15, 'Bridges', '/icons/bridges.svg', 0);
INSERT INTO category (id, name, image, accessories_count) VALUES (16, 'Range Extenders', '/icons/rangeextenders.svg', 0);
